#!/bin/bash

source ~/myconfig/scrbrightstub
sudo chmod ugo+w ${bright_file_path}brightness
source ~/myconfig/kbdbrightstub
sudo chmod ugo+w ${bright_file_path}brightness
#sudo chmod ugo+w /sys/class/backlight/intel_backlight/brightness
#sudo chmod ugo+w /sys/class/leds/smc\:\:kbd_backlight/brightness
